package com.trms.data.Impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import com.trms.data.StatusDAO;
import com.trms.factory.ConnectionFactory;
import com.trms.models.Status;

public class StatusDAOImpl implements StatusDAO {

	Connection connection;
	
	public StatusDAOImpl() {
		connection = ConnectionFactory.getConnection();
	}
	
	
	
	public long create(Status newStatus) {
		String sql = "Insert into Status(id,status_name)" + 
					"Values(default,?);";
		
		try {
		PreparedStatement preparedStatement = connection.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
		
		preparedStatement.setString(1,newStatus.getStatusName());
		
		int count = preparedStatement.executeUpdate();
		
		ResultSet resultSet = preparedStatement.getGeneratedKeys();
		
		if(count>0) {
			System.out.println("Status added!");
			// return the id generated by this entry
			resultSet.next();
			int id = resultSet.getInt(1);
			return id;
		}
		}
		catch(SQLException e) {
			e.printStackTrace();
			System.out.println("Something went wrong!");
		}
		
		return -1L;
	}

	public Status getById(long id) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Status> getAll() {
		// TODO Auto-generated method stub
		return null;
	}

	public void update(Status updatedObj) {
		// TODO Auto-generated method stub
		
	}

	public void delete(Status objToDelete) {
		// TODO Auto-generated method stub
		
	}

}
